import { loader } from 'fumadocs-core/source';
// `.source/` is generated by fumadocs-mdx (on `next dev` / `next build`, or `npx fumadocs-mdx`).
import { docs } from '../../../.source';
import { docsI18n } from './i18n';

export const source = loader({
  baseUrl: '/docs',
  i18n: docsI18n,
  source: docs.toFumadocsSource(),
});
